### ISSUE TITLE
Cannot compile the plugin

### ISSUE THREAD

**Issue by MarkarianFR** [Seggan/SFCalc#25]
Hi,

I've downloaded this addon without any editions and it doensn't compile.
Only getting :
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SFCalc: Fatal error compiling

Using JDK 16 and JRE 1.8.0_301.
FYI : I have no errors with other addons/slimefun plugin.

Thank you per advance for your support.

Markarian

**Comment by Seggan** [comment]
Known issue with JDK 16. I am leaving home until Monday, will fix then

**Comment by MarkarianFR** [comment]
Thank you. Waiting until resolution.

**Comment by Seggan** [comment]
May I ask why you are compiling instead of downloading from [the builds page](https://thebusybiscuit.github.io/builds/Seggan/SFCalc/master)?

**Comment by Seggan** [comment]
Fixed

**Comment by MarkarianFR** [comment]
Sorry, didn't saw ur question.
Just for answer, it's because i'm forking your repo and working inside. (Translations etc)

**Comment by Seggan** [comment]
But you can already edit messages in the config

**Comment by MarkarianFR** [comment]
This is not only for that. I'm trying in lot of addons some things.
And the bug is still here.
"Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SFCalc: Fatal error compiling" (command used is maven clean package)

**Comment by Seggan** [comment]
Can I see full maven log?

**Comment by MarkarianFR** [comment]
[logs.txt](https://github.com/Seggan/SFCalc/files/6977382/logs.txt)


In attachments

**Comment by MarkarianFR** [comment]
Woops. The first logs are wrong.
Please check the second in attachment. Sorry for the first.
[logs.txt](https://github.com/Seggan/SFCalc/files/6977406/logs.txt)

**Comment by Seggan** [comment]
Thanks, that gets to the heart of the problem. Fixed.

**Comment by MarkarianFR** [comment]
Seems working now. Thank you for your reactivity.
